import React from 'react'

export const metadata = {
  title: "About PAge" ,
  description: "Generated by Gustavo",
  keywords: ["About Page", 'fernando', 'nextjs', 'practica']
};


export default function AboutPage() {
  return (
    
      
      <span className='text-7xl'>About Page</span>
    
  )
}


