import localFont from "next/font/local";
import { Montserrat } from 'next/font/google'
import "./globals.css";

const inter = Montserrat({ subsets: ['latin'] })


export const metadata = {
  title: "Gustavo's Home Page",
  description: "Generated by Vercel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
